name: Test untrusted input
run-name: PR head `${{ github.head_ref }}`

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildExtensionBundle:
    name: Build extension bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          echo "CI_BRANCH=${HEAD_REF}" >> $GITHUB_ENV

      - shell: bash
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          echo "test 123" > ./README.md
          git add ./README.md
          git commit -q -m "Update README from ${HEAD_REF} branch."
          git log
